Integration TypeSctipt
haliant/new-project pull request #2
Opened 2021-04-22 18:54 UTC by haliant

2021-04-22 20:11 UTC, mike-gusiev requested changes

2021-04-22 20:11 UTC, mike-gusiev commented on src/api.ts
> +	private apiUrlHouse = 'http://demo0725221.mockable.io/1';
- классы считаються уже устаревшими. сделай в виде singleton-а (через curly braces), либо просто функциями
- вынеси домен в отдельную константу

2021-04-22 20:11 UTC, mike-gusiev commented on src/components/app/App.tsx
>  			<Route path="/" component={MainPage} exact />
пытайся код сделать более лаконичным. вместо:
```
render={({ match }) => {
	const { id } = match.params;
	return <HousePage id={id} />;
}}
```

можно было сделать:
```
render={({ match }) => (<HousePage id={match.params.id} />)}
```

2021-04-22 20:11 UTC, mike-gusiev commented on src/components/housePage/housePage.tsx
>  import React, { useEffect } from 'react';
избавься от лишних папок в src/components и в src/styled. нету смысла там создавать дополнительные папки

2021-04-22 20:11 UTC, mike-gusiev commented on src/components/mainPage/mainPage.tsx
> +		const request = () => dispatch(updateHousesListRequest());
а какой смысл был создавать эту переменную? почему сразу dispatch не вызвать?

2021-04-22 20:11 UTC, mike-gusiev commented on src/components/housePage/housePage.tsx
>  		body: { images, title, price, seller, address, body },
не всегда есть смысл делать подробную деструктуризацию. особенно если это затрудняет чтение кода. и приходиться долго искать откуда данные беруться

2021-04-22 20:11 UTC, mike-gusiev commented on src/components/spinnerComponent/spinnerComponent.tsx
> +		<Spinner animation="border" variant="primary" role="status"></Spinner>
этот тег должен быть одинарным

2021-04-22 20:11 UTC, mike-gusiev commented on src/components/spinnerComponent/spinnerComponent.tsx
>  	display: 'flex',
не используй инлайновые js стили. повыноси все в styled components

2021-04-23 07:10 UTC, haliant commented on src/components/mainPage/mainPage.tsx
> +		const request = () => dispatch(updateHousesListRequest());
Мой затуп, до тс запись была такой

2021-04-23 07:14 UTC, haliant commented on src/components/mainPage/mainPage.tsx
> +		const request = () => dispatch(updateHousesListRequest());
Мой затуп, до ТС запись была такой:
useEffect(() => dispatch(updateHousesListRequest()), [dispatch])
И конечно же не работала, потому что диспатч получается возвращался, а должен просто выполнится. Вот после добавление ТС и была ошибка и исправить удалось таким способом, почему-то не догадался просто добавить скобки и вызвать, что вроде как логично

2021-04-23 08:59 UTC, mike-gusiev requested changes

2021-04-23 08:59 UTC, mike-gusiev commented on src/api.ts
> +		getInstance: () => {
используй кратки формы там где это возможно:
`getInstance: () => instance || (instance = createInstance()),`

2021-04-23 09:08 UTC, merged